/** A named output variant (e.g. "original", "optimized", "thumbnail"). */
export type PipelineVariant = string;

/** Input source fed into a pipeline — a file/blob with metadata. */
export type PipelineSource = {
  /** The raw file or blob data. */
  file: File | Blob;
  /** Original filename (with extension). */
  name: string;
  /** MIME type (or "application/octet-stream" if unknown). */
  type: string;
  /** Relative directory path when dropped from a folder. */
  relativePath?: string;
};

/** A single output artifact produced by a pipeline stage. */
export type PipelineArtifact = {
  /** Artifact variant label. */
  variant: PipelineVariant;
  /** The output file or blob. */
  file: File | Blob;
  /** Basename for upload metadata `filename` (includes extension). */
  filename: string;
  /** MIME for upload metadata `filetype`. */
  filetype: string;
  /** Original relative path if sourced from a folder drop. */
  relativePath?: string;
};

/** Informational or warning message emitted during pipeline execution. */
export type PipelineInfoMessage = {
  /** Severity level. */
  level: "info" | "warn";
  /** Human-readable message. */
  message: string;
  /** Machine-readable code for programmatic handling. */
  code?: string;
};

/** Result produced by a completed pipeline run. */
export type PipelineResult = {
  /** Artifacts generated by pipeline stages. */
  artifacts: PipelineArtifact[];
  /** Info/warning messages collected during execution. */
  info: PipelineInfoMessage[];
  /**
   * True when the source should be removed from the queue (e.g. junk files in
   * folder drops). False when we keep the row but it has no uploadable outputs.
   */
  removeFromQueue: boolean;
};

/** Logger function injected into pipeline context. */
export type PipelineLogger = (
  /** Log severity. */
  level: "debug" | "info" | "warn" | "error",
  /** Log message. */
  message: string,
  /** Optional structured payload. */
  extra?: unknown,
) => void;

/** Context object passed to every pipeline stage. */
export type PipelineContext = {
  /** Logger for emitting debug/info/warn/error messages. */
  log: PipelineLogger;
};

/** Decision returned by a stage's `when` guard: run the stage or skip it. */
export type StageDecision = { run: true } | { run: false; reason?: string; code?: string };

/** A single processing stage in a pipeline definition. */
export type PipelineStage<I, O> = {
  /** Unique stage identifier. */
  id: string;
  /** Guard: decides whether this stage should run for the given input. */
  when: (input: I, ctx: PipelineContext) => Promise<StageDecision> | StageDecision;
  /** Execute the stage and produce output. */
  run: (input: I, ctx: PipelineContext) => Promise<O> | O;
  /** Optional error handler — can throw, skip, or fallback to a value. */
  onError?: (
    error: unknown,
    input: I,
    ctx: PipelineContext,
  ) =>
    | Promise<
        | { action: "throw" }
        | { action: "skip"; info?: PipelineInfoMessage }
        | { action: "fallback"; value: O; info?: PipelineInfoMessage }
      >
    | { action: "throw" }
    | { action: "skip"; info?: PipelineInfoMessage }
    | { action: "fallback"; value: O; info?: PipelineInfoMessage };
};

/** Ordered list of stages forming a complete processing pipeline. */
export type PipelineDefinition<I, O> = {
  /** Stages executed in order; each receives the output of the previous merge. */
  stages: Array<PipelineStage<I, O>>;
};
